services:
  - type: web
    name: weatherready-live
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free

cron:
  jobs:
    - name: update-forecast
      schedule: "@daily"
      command: "python main.py"
