services:
  - type: web
    name: weatherready-live
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free

  - type: cron
    name: update-forecast
    env: python
    schedule: "@daily"
    command: "python main.py"
    plan: free
